import type { Metadata } from "next";
import "./globals.css";
import GradientBlinds from "@/components/GradientBlinds";

// Removed Google Geist fonts to ensure Helvetica Neue is used project-wide

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* Background gradient, fixed and behind all content */}
        <GradientBlinds />
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
